### ISSUE TITLE
为什么注释掉了 data_syn.py 中 init() 中开头的部分初始化代码？

### ISSUE THREAD

**Issue by codezealot** [AlexLiue/tushare_sync#1]
为什么注释掉了 data_syn.py 中 init() 中开头的部分初始化代码？
https://github.com/AlexLiue/tushare_sync/blob/master/data_syn.py#L40

像 trade_cal.init() ，append并没有直接调用init

**Comment by AlexLiue** [comment]
这个是测试代码，当时是同步调用过于频繁超 Tushare 限额，导致异常中断，再次重新初始化注释掉了已同步完成的表 ，把注释取消掉就可以了

**Comment by AlexLiue** [comment]
已修复
