### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by a21211** [AlexLiue/tushare_sync#2]
建议：
1、tushare数据并非全部从2016年开始，可以使用空值传入获取所有日期数据
2、append指定日期有些不妥，最好能根据查询最后一条记录，获取append开始日期
3、数据表没有主键和索引查询和添加都很慢

**Comment by a21211** [comment]
4、apend开始如果有些表没有初始化会忽略，建议查询表不存在的话，调用init

**Comment by AlexLiue** [comment]
多谢提交的建议
建议1：数据开始日期，不同数据表不太一样，当前是 tushare 页面接口测试后，获取的最早的日期， 日期传入空值 Tushare 深翻页查询存在性能问题，如翻页到30页后，查询返回延迟剧增，因此查询接口需指定查询日期
建议2、3、4：是很不错的提议，后面有空了我修改下，或者欢迎提交 PR
:

**Comment by AlexLiue** [comment]
已更新代码

**Comment by AlexLiue** [comment]
关闭
